version: '3'

networks:
   shoppingcart:

services:
   db:
      build: .
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports: 
         - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: admin
      networks: 
      - shoppingcart
   phpmyadmin:
      image: phpmyadmin
      restart: always
      ports: 
         - 8081:80
      environment: 
         PMA_HOST: db
      networks: 
         - shoppingcart
   api:
      build: ./api
      ports: 
         - 5000:5000
      networks: 
         - shoppingcart
